#!/usr/bin/python3

print("*********************** Domain To IP Convertor *************************")

print("*********************** Create By 0xSinper_IU  *************************")

import socket 

Domain_Name = input("Please , Enter Domain name : ")

ip = socket.gethostbyname(Domain_Name)

print("IP For {} : {}".format(Domain_Name,ip))


print("Thank For Using Me -_- ")
